source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'


target 'ZRequestTool' do

  use_frameworks!

  pod 'Moya', '~> 14.0'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'Moya/ReactiveSwift', '~> 14.0'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'SwiftyJSON'
  pod 'HandyJSON'
end
